
-- 世界那么大还是想遇见你
local source = {}

-- 一分钟80拍
source["bpm"] = 130
-- beat_n一个小节有n拍，
source["beat_n"] = 4
-- beat_m分音符为一拍
source["beat_m"] = 4

local chords = source["chords"]

source["music"] = {}
music = source["music"]

-- rc:唱名,音高  note:代表时值，如4分音符，8分音符
chapters = {
    -- 1
    {["note"] = 4, ["chord"] = "1,5"},
    {["note"] = 4},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    -- 2
    {["note"] = 4, ["chord"] = "_6,1_"},
    {["note"] = 4},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    -- 3
    {["note"] = 4, ["chord"] = "4,4_"},
    {["note"] = 4},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 16, ["chord"] = "4_"},
    {["note"] = 16, ["chord"] = "3_"},
    {["note"] = 4, ["chord"] = "1_"},
    -- 4
    {["note"] = 4, ["chord"] = "2,2_"},
    {["note"] = 4},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    -- 5
    {["note"] = 4, ["chord"] = "_5,5"},
    {["note"] = 4, ["chord"] = "2,5,7,5"},
    {["note"] = 4},
    {["note"] = 4},
    -- 6(.S.,||:,反复标记)（循环第一轮开始）
    {["note"] = 8, ["chord"] = "1,3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 7
    {["note"] = 8, ["chord"] = "_7,2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 8
    {["note"] = 8, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 9
    {["note"] = 8, ["chord"] = "_5,7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "5"},
    -- 10
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "6_"},
    {["note"] = 4, ["chord"] = "2,5,7,5_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "4_"},

    -- 11
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 4, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    -- 12
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    -- 13(:||)（循环第一轮结束）
    {["note"] = 8, ["chord"] = "1,1_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 4, ["chord"] = "3_"},
    {["note"] = 4, ["chord"] = "3,5,1,3_"},
    {["note"] = 4},
    -- 6（循环第二轮开始）
    {["note"] = 8, ["chord"] = "1,3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 7
    {["note"] = 8, ["chord"] = "_7,2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 8
    {["note"] = 8, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 9
    {["note"] = 8, ["chord"] = "_5,7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "5"},
    -- 10
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "6_"},
    {["note"] = 4, ["chord"] = "2,5,7,5_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "4_"},

    -- 11
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 4, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    -- 12
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    -- 13（循环第二轮结束）
    {["note"] = 8, ["chord"] = "1,1_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 4, ["chord"] = "3_"},
    {["note"] = 4, ["chord"] = "3,5,1,3_"},
    {["note"] = 4},
    -- 14
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 4},
    -- 15
    {["note"] = 8, ["chord"] = "_6,2_"},
    {["note"] = 16},
    {["note"] = 16, ["chord"] = "5_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 4, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 16, ["chord"] = "1_"},
    {["note"] = 16, ["chord"] = "7"},
    -- 16
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "6,1_,4_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    -- 17
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 4, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    -- 18
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 8, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 19
    {["note"] = 8, ["chord"] = "4,4_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "4_"},
    -- 20
    {["note"] = 8, ["chord"] = "_5,3_"},
    {["note"] = 4, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2,5,2_"},
    {["note"] = 4},
    {["note"] = 4},
    -- 21
    {["note"] = 8, ["chord"] = "1,3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    -- 22
    {["note"] = 8, ["chord"] = "_7,2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 23
    {["note"] = 8, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 24
    {["note"] = 8, ["chord"] = "_5,7"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "5"},

    -- 25
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "6_"},
    {["note"] = 4, ["chord"] = "2,5,7,5_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "4_"},
    -- 26
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 4, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    -- 27
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    -- 28
    {["note"] = 4, ["chord"] = "1,1_"},
    {["note"] = 4},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 4, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "5_"},
    -- 29
    {["note"] = 8, ["chord"] = "_3"},
    {["note"] = 8, ["chord"] = "3"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    -- 30
    {["note"] = 8, ["chord"] = "_6"},
    {["note"] = 8, ["chord"] = "4"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 31
    {["note"] = 8, ["chord"] = "4,4_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "4_"},
    -- 32
    {["note"] = 8, ["chord"] = "_5,3_"},
    {["note"] = 4, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "5,7,2_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 4, ["chord"] = "4_"},
    -- 33
    {["note"] = 8, ["chord"] = "_3,5_"},
    {["note"] = 8, ["chord"] = "3"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    -- 34
    {["note"] = 8, ["chord"] = "_3,5_"},
    {["note"] = 8, ["chord"] = "3"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    -- 35
    {["note"] = 8, ["chord"] = "_6"},
    {["note"] = 8, ["chord"] = "3"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 36
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "6_"},
    -- 37
    {["note"] = 4, ["chord"] = "4"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    -- 38
    {["note"] = 8, ["chord"] = "_5"},
    {["note"] = 4, ["chord"] = "2_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "2"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    -- 39(D.S.)
    {["note"] = 4, ["chord"] = "2,5,7,5_"},
    {["note"] = 4},
    {["note"] = 4},
    {["note"] = 4},

    -- 5 （跳回5小节）
    {["note"] = 4, ["chord"] = "_5,5"},
    {["note"] = 4, ["chord"] = "2,5,7,5"},
    {["note"] = 4},
    {["note"] = 4},
    -- 6
    {["note"] = 8, ["chord"] = "1,3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "4_"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 7
    {["note"] = 8, ["chord"] = "_7,2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 8, ["chord"] = "5"},
    -- 8
    {["note"] = 8, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "3_"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    -- 9
    {["note"] = 8, ["chord"] = "_5,7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "5"},
    -- 10
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "5_"},
    {["note"] = 8, ["chord"] = "6_"},
    {["note"] = 4, ["chord"] = "2,5,7,5_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "4_"},

    -- 11
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 4, ["chord"] = "_6,1_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    -- 12
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "2_"},
    {["note"] = 8, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "6"},
    {["note"] = 8, ["chord"] = "7"},
    -- 13
    {["note"] = 8, ["chord"] = "1,1_"},
    {["note"] = 8, ["chord"] = "5"},
    {["note"] = 4, ["chord"] = "3_"},
    {["note"] = 4, ["chord"] = "3,5,1,3_"},
    {["note"] = 4},

    -- 37
    {["note"] = 4, ["chord"] = "1,3_"},
    {["note"] = 4},
    {["note"] = 4, ["chord"] = "_7,2_"},
    {["note"] = 4},
    -- 38
    {["note"] = 6, ["chord"] = "_6,2_"},
    {["note"] = 6, ["chord"] = "5_"},
    {["note"] = 6, ["chord"] = "2_"},
    {["note"] = 4, ["chord"] = "_5,1_"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 16, ["chord"] = "1_"},
    {["note"] = 16, ["chord"] = "7"},
    -- 39
    {["note"] = 4, ["chord"] = "4,6"},
    {["note"] = 8, ["chord"] = "7"},
    {["note"] = 8, ["chord"] = "1_"},
    {["note"] = 4, ["chord"] = "4,6,1,4_"},
    {["note"] = 8},
    {["note"] = 8, ["chord"] = "1_"},
    -- 40
    {["note"] = 4, ["chord"] = "3,5,7,3_"},
    {["note"] = 4},
    {["note"] = 4},
    {["note"] = 4},

}

table.insert(music, chapters)
    
return source