-- love story
    local source = {}

    -- 一分钟80拍
    source["bpm"] = 120
    -- beat_n一个小节有n拍，
    source["beat_n"] = 4
    -- beat_m分音符为一拍
    source["beat_m"] = 4

    local chords = source["chords"]

    source["music"] = {}
    music = source["music"]

    -- rc:唱名,音高  note:代表时值，如4分音符，8分音符
    -- 第一小节
    chapter_1 = {
        {["note"] = 8, ["chord"] = "1,3"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,1_"},

        {["note"] = 8, ["chord"] = "1,3"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,1_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},

        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_6,6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,7"},
        {["note"] = 8, ["chord"] = "_6,7"},
        {["note"] = 8, ["chord"] = "_6,5"},

        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,6"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,5"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        --||:循环
        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,1_"},

        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_6,6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,7"},
        {["note"] = 8, ["chord"] = "_6,6"},
        {["note"] = 8, ["chord"] = "_6,5"},

        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,6"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_5,7"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "1,5_"},
        {["note"] = 8, ["chord"] = "1,4_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1,2_"},

        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,4_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,5,1_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,1_,4_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "1,3,5,1_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,4,6,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_4,4,6,1_,3_"},
        {["note"] = 8, ["chord"] = "_4"},
        
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 4, ["chord"] = "_5,5,7,3_"},
        {["note"] = 4, ["chord"] = "_5,3_"},
        {["note"] = 16, ["chord"] = "7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 16},

        {["note"] = 8, ["chord"] = "1,3"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,1_"},
        
        {["note"] = 8, ["chord"] = "1,3"},
        {["note"] = 8, ["chord"] = "1,5"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,5"},
        -------------第一遍循环------- :||

        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,1_"},

        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,7"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_6,6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,5"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,7"},
        {["note"] = 8, ["chord"] = "_6,6"},
        {["note"] = 8, ["chord"] = "_6,5"},

        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,6"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,1_"},

        {["note"] = 8, ["chord"] = "_5,7"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,1_"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "1,5_"},
        {["note"] = 8, ["chord"] = "1,4_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1,2_"},

        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,4_"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},
        {["note"] = 8},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,5,1_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,1_,4_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "1,3,5,1_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "_4,2,5,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "_4,2,5,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_4,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,2,5,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,4,6,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_4,4,6,2_,3_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 4, ["chord"] = "_5,5,7,3_"},
        {["note"] = 4, ["chord"] = "_5,3_"},
        {["note"] = 16, ["chord"] = "7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 16},

        {["note"] = 8, ["chord"] = "_1,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,1_,4_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "1,3,5,1_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_1,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,4_"},
        {["note"] = 8, ["chord"] = "5_"},
        {["note"] = 4, ["chord"] = "_5,2,5,2_"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,4,6,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_4,4,6,1_,3_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 4, ["chord"] = "_5,5,7,3_"},
        {["note"] = 4, ["chord"] = "_5,3_"},
        {["note"] = 16, ["chord"] = "7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 16},

        {["note"] = 8, ["chord"] = "_1,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,1_,4_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_1,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_6,4_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,6,1_,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3,6,1_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_6,7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,3,6,7"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "4"},

        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,4,6,1_"},
        {["note"] = 8, ["chord"] = "7"},
        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "5"},

        {["note"] = 8, ["chord"] = "_5,5"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "7"},

        {["note"] = 8, ["chord"] = "_6,7"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "3"},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "_4,6"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "4_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "2_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "7"},
        {["note"] = 8, ["chord"] = "7"},

        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "3,3_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "1,5_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "2_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "5"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,3_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "_6,1_"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,2_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        ---------------
        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,5,1_,4_"},
        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "1,3,5,1_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "1,1_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3,5,2_"},
        {["note"] = 8, ["chord"] = "1"},

        {["note"] = 8, ["chord"] = "_5,1_"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "_5,2,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "_5,5_"},
        {["note"] = 8, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "_5,5,7,3_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,2,5,1_"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_6,2_"},
        {["note"] = 8, ["chord"] = "3_"},
        {["note"] = 8, ["chord"] = "_6,3,6,2_"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "_4,1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4,4,6,2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "_4,3_"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_4,4,6,1_,3_"},
        {["note"] = 8, ["chord"] = "_4"},

        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_5,5,2_,3_"},
        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_5,5,2_"},
        {["note"] = 8, ["chord"] = "_5"},

        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_3,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 4, ["chord"] = "1,3,5,2_"},

        {["note"] = 8, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_3,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 4, ["chord"] = "1,3,5,2_"},

        {["note"] = 8, ["chord"] = "_5"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,3,5,2_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_5,3_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 4, ["chord"] = "_5,3,5,2_"},

        {["note"] = 8, ["chord"] = "_6,1_"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "7"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 4, ["chord"] = "5"},
        {["note"] = 8, ["chord"] = "_6"},

        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "3"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 8, ["chord"] = "2"},
        {["note"] = 8, ["chord"] = "_6"},
        {["note"] = 4, ["chord"] = "1"},
        {["note"] = 8, ["chord"] = "5"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 4, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "_4,7"},
        {["note"] = 8, ["chord"] = "1_"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 8, ["chord"] = "2_"},
        {["note"] = 8, ["chord"] = "_4"},
        {["note"] = 8, ["chord"] = "4"},
        {["note"] = 4, ["chord"] = "6"},
        {["note"] = 8, ["chord"] = "1_"},

        {["note"] = 8, ["chord"] = "1"},
    
    }
    table.insert(music, chapter_1)
    
    return source